#!/bin/bash

#backup default or existant configuration
[ -e /etc/bluetooth/audio.conf.xbian ] || cp /etc/bluetooth/audio.conf /etc/bluetooth/audio.conf.xbian
[ -e /etc/bluetooth/main.conf.xbian ] || cp /etc/bluetooth/main.conf /etc/bluetooth/main.conf.xbian

sed -i --follow-symlinks 's/Enable=[^ ]*/Enable=Source,Sink,Media/g' /etc/bluetooth/audio.conf
if [ $(grep "Enable=Source,Sink,Media" /etc/bluetooth/audio.conf | wc -l) -eq 1 ];	then
	echo "Success: replaced bluetooth enable"
else
	sed -i --follow-symlinks 's/^\[General\]/\[General\]\nEnable=Source,Sink,Media/g' /etc/bluetooth/audio.conf
	echo "Success: insert bluetooth enable"
fi
sed -i --follow-symlinks 's/Name = [^ ]*/Name = %h/g' /etc/bluetooth/main.conf
sed -i --follow-symlinks 's/Class = [^ ]*/Class = 0x20041C/g' /etc/bluetooth/main.conf

xbian-config services insert bluetooth-pairing
xbian-config services insert bluetooth

chmod 664 /etc/xbian-a2dp.conf
