#!/bin/bash

#backup default or existant configuration
[ -e /etc/bluetooth/audio.conf.xbian ] || cp /etc/bluetooth/audio.conf /etc/bluetooth/audio.conf.xbian
[ -e /etc/pulse/daemon.conf.xbian ] || cp /etc/pulse/daemon.conf /etc/pulse/daemon.conf.xbian
[ -e /etc/bluetooth/main.conf.xbian ] || cp /etc/bluetooth/main.conf /etc/bluetooth/main.conf.xbian

sed -i 's/^resample-method /; resample-method /' /etc/pulse/daemon.conf
echo 'resample-method = trivial' >> /etc/pulse/daemon.conf

sed -i --follow-symlinks 's/Enable=[^ ]*/Enable=Source,Sink,Media,Socket/g' /etc/bluetooth/audio.conf
if [ $(grep "Enable=Source,Sink,Media,Socket" /etc/bluetooth/audio.conf | wc -l) -eq 1 ];	then
	echo "Success: replaced bluetooth enable"
else
	sudo sed -i --follow-symlinks 's/^\[General\]/\[General\]\nEnable=Source,Sink,Media,Socket/g' /etc/bluetooth/main.conf
	echo "Success: insert bluetooth enable"
sed -i --follow-symlinks 's/Name = [^ ]*/Name = %h/g' /etc/bluetooth/main.conf
sed -i --follow-symlinks 's/Class = [^ ]*/Class = 0x20041C/g' /etc/bluetooth/main.conf

xbian-config services insert bluetooth-pairing
xbian-config services insert bluetooth

chmod 664 /etc/xbian-a2dp.conf

    
