#!/bin/sh

#add user xbian to the Pulse audio group  
usermod -G lp -a xbian

#load snd_bcm2835 module
modprobe snd_bcm2835
grep -q 'snd_bcm2835' /etc/modules || echo 'snd_bcm2835' >> /etc/modules


 

