#!/bin/sh

#add user xbian to the Pulse audio group  
usermod -G lp -a xbian

#load snd_bcm2835 module
modprobe snd_bcm2835
grep -q 'snd_bcm2835' /etc/modules || echo 'snd_bcm2835' >> /etc/modules

#backup default or existant configuration
[ -e /etc/bluetooth/audio.conf.xbian ] || cp /etc/bluetooth/audio.conf /etc/bluetooth/audio.conf.xbian
[ -e /etc/pulse/daemon.conf.xbian ] || cp /etc/pulse/daemon.conf /etc/pulse/daemon.conf.xbian
[ -e /etc/bluetooth/main.conf.xbian ] || cp /etc/bluetooth/main.conf /etc/bluetooth/main.conf.xbian

sed -i 's/^resample-method /; resample-method /' /etc/pulse/daemon.conf
echo 'resample-method = trivial' >> /etc/pulse/daemon.conf

sed -i --follow-symlinks 's/Enable=[^ ]*/Enable=Source,Sink,Media,Socket/g' /etc/bluetooth/audio.conf
sed -i --follow-symlinks 's/Name = [^ ]*/Name = %h/g' /etc/bluetooth/main.conf
sed -i --follow-symlinks 's/Class = [^ ]*/Class = 0x20041C/g' /etc/bluetooth/main.conf
 

